apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: python
      command: ["/bin/bash", "-c"]
      args:
        - "hello world!!!!!!!-gitTrigger"
        - set -e -o pipefail;
          echo "Cloning REPOSITORY";
