apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  inputs:
    params:
      - name: repository
        type: string
        value: https://github.com/SudhaManu1/Tekton-Tutorial
      - name: branch
        type: string
        value: master
  steps:
    - name: echo
      image: ubuntu:18.04
      command:
        - echo
      args:
        - "hello world from $(inputs.params.repository):$(inputs.params.branch)!!!!"
