apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: hello-trigger-template
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
    - name: path
      description: level-2 path in repo
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: hello-pipeline
        params:
          - name: repository
            value: "https://github.com/SudhaManu1/Tekton-Tutorial.git"
          - name: branch
            value: "bug"
          - name: path
            value: "level-2/.tekton"


